version: "3"

tasks:
  default:
    cmds:
      - task: config
      - task: build

  config:
    cmds:
      - mkdir -p build
      - cmake -B build -G Ninja ./OpenBLAS-0.3.29

  build:
    cmds:
      - ninja -C build

  patch:
    dir: OpenBLAS-0.3.29
    cmds:
      - patch -p 1 < ../patch/0001-Fix-function-prototypes.patch
      - patch -p 1 < ../patch/0002-Fix-empty-prototypes-of-select-selctg.patch
